-- Run this in Supabase SQL Editor (https://supabase.com/dashboard)
-- 1. Create the leaderboard table
create table if not exists leaderboard (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  timestamp bigint,
  player_name text not null,
  player_tag text not null,
  level_id text not null,
  time_ms integer not null,
  char_count integer not null
);

-- 2. Enable Row Level Security (RLS)
alter table leaderboard enable row level security;

-- 3. Allow anyone to read the leaderboard (for public booth displays)
create policy "Anyone can read leaderboard"
  on leaderboard for select
  using (true);

-- 4. Allow anyone to submit their score
create policy "Anyone can insert scores"
  on leaderboard for insert
  with check (true);

-- 5. (Optional) Allow booth admin to clear scores
create policy "Anyone can clear scores"
  on leaderboard for delete
  using (true);
